baseURL = "https://arno.netlify.app/"
languageCode = "en-us"
title = "Arno Van den Hende - Photosopher"
paginate = 10

[menu]

  [[menu.main]]
    name = "Photos"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  # removed, added to frontmatter of about page itself to render it active
  #
  #[[menu.main]]
  #  name = "About"
  #  url = "/about/"
  #  weight = 3

[permalinks]
    blog = "/:section/:year/:filename/"
    page = "/:slug/"
    photo = "/:section/:year/:filename/"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"
    
[params]
    dateFormat = "January 2006"

[frontmatter]
date = ["publishDate", "date", "lastmod"]
publishDate = ["publishDate", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = false
      xhtml = false
      
enableEmoji = "True"