baseURL = "http://example.org/"
languageCode = "en-us"
title = "Arno Van den Hende - Photosopher"
paginate = 2

[permalinks]
    blog = "/:section/:year/:month/:slug/"
    page = "/:slug/"
    photo = "/:section/:year/:month/:slug/"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"
    
[params]
    dateFormat = "January 2006"

[frontmatter]
date = ["publishDate", "date", "lastmod"]
publishDate = ["publishDate", "date"]

blackfriday = ["True"]