baseURL = "https://arno.netlify.com/"
languageCode = "en-us"
title = "Arno Van den Hende - Photosopher"
paginate = 10

[menu]

  [[menu.main]]
    name = "Photo's"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[permalinks]
    blog = "/:section/:year/:month/:slug/"
    page = "/:slug/"
    photo = "/:section/:year/:month/:slug/"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"
    
[params]
    dateFormat = "January 2006"

[frontmatter]
date = ["publishDate", "date", "lastmod"]
publishDate = ["publishDate", "date"]

blackfriday = ["True"]